#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

fail() {
  echo "ERROR: ${*}"
  exit 2
}

usage() {
  cat <<-EOM
USAGE: ${0##*/} [root domain] [record type - A or CNAME]
e.g. ${0##*/} example.com CNAME
EOM
  exit 1
}

if [[ $# != 2 ]]; then
  usage
fi

# 원하는 도메인의 record sets을 추출
hosted_zone_name=${1}

## read hosted-zones
# 여기서 hosted-zones ID를 얻어서
hosted_zone_id=$(aws route53 list-hosted-zones --output text | grep ${hosted_zone_name} | awk '{print $3}')

# 여기서 hosted-zone의 record-set을 조회한다
type=${2}
case ${type} in
  A)
    aws route53 list-resource-record-sets --hosted-zone-id ${hosted_zone_id} | jq -r '.ResourceRecordSets[] | select(.Type=="A") | "\(.Name) / \(.AliasTarget.DNSName)"'
  ;;
  CNAME)
    aws route53 list-resource-record-sets --hosted-zone-id ${hosted_zone_id} | jq -r '.ResourceRecordSets[] | select(.Type=="CNAME") | "\(.Name) / \(.ResourceRecords[0].Value)"'
  ;;
  *)
    echo "not supported type"
  ;;
esac
