#!/bin/bash
 
security_groups=$(aws ec2 describe-security-groups --query "SecurityGroups[].[GroupId, GroupName, Description]" --output text)
 
while read -r line; do
    sg_id=$(echo $line | awk '{print $1;}')
    sg_name=$(echo $line | awk '{print $2;}')
    sg_desc=$(echo $line | awk '{ for(i=3; i<=NF; ++i) printf $i""FS; print "" }')
    network_interface_lenght=$(aws ec2 describe-network-interfaces --filters "Name=group-id,Values=$sg_id" --query "length(NetworkInterfaces)" --output text)
    if [ ${network_interface_length} == 0 ]; then
      echo "${sg_id},${sg_name},${sg_desc}"
    fi
done <<< "${security_groups}"

