#!/bin/bash
 
sgs=$(aws ec2 describe-security-groups --query "SecurityGroups[].[GroupId, GroupName]" --output text)
 
while read -r line; do
  sg_id=$(echo $line | awk '{print $1;}')
  sg_name=$(echo $line | awk '{print $2;}')
  network_interface_lenght=$(aws ec2 describe-network-interfaces --filters "Name=group-id,Values=$sg_id" --query "length(NetworkInterfaces)" --output text)
  echo "${sg_id},${network_interface_lenght},${sg_name}"
done <<< "$sgs"
